import type { AtlassianSource } from '@akc/shared';
import { streamConfiguredLlmSummary, testConfiguredLlmConnection } from '../services/llm/llmProviderFactory.js';
import { getLlmRuntimeConfig, readResolvedLlmSettings } from '../services/settings/llmSettingsStore.js';

const settings = readResolvedLlmSettings();
const runtimeConfig = getLlmRuntimeConfig();

if (!runtimeConfig) {
  console.info(JSON.stringify({
    status: 'skipped',
    provider: settings.provider,
    source: settings.source,
    configured: settings.configured,
    enabled: settings.enabled,
    reason: settings.statusMessage
  }, null, 2));
  process.exit(0);
}

const testResult = await testConfiguredLlmConnection(runtimeConfig);
console.info(JSON.stringify({
  status: testResult.ok ? 'connection-ok' : 'connection-failed',
  provider: runtimeConfig.provider,
  source: runtimeConfig.source,
  model: runtimeConfig.model,
  message: testResult.message
}, null, 2));

if (!testResult.ok) {
  process.exitCode = 1;
} else {
  const smokeSources: AtlassianSource[] = [
    {
      id: 'SMOKE-1',
      sourceType: 'jira',
      origin: 'real',
      title: 'LLM smoke test source',
      summary: 'Connection smoke test source generated by the broker script.',
      relevanceScore: 100,
      url: 'https://example.atlassian.net/browse/SMOKE-1',
      actionId: 'smoke_llm',
      retrievedAt: new Date().toISOString(),
      metadata: { jira: { key: 'SMOKE-1' } }
    }
  ];
  let failed = false;
  for await (const event of streamConfiguredLlmSummary({
    question: 'Summarize the provided smoke test source.',
    sources: smokeSources,
    messageId: 'msg_smoke_llm'
  }, runtimeConfig)) {
    console.info(JSON.stringify(event));
    if (event.type === 'llm.failed') failed = true;
  }
  if (failed) process.exitCode = 1;
}
